djangotodo/urls.py
from django.urls import path, include
from django.contrib.auth import views
from django.contrib import admin  
from todo import views
from shotdogs import views
from veronahuang import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    path('index/', include('todo.urls')),
    path('flight/', include('todo.urls')),
    path('wedding/', include('todo.urls')),
    path('shotdog/', include('shotdogs.urls')),
    path('verona/', include('veronahuang.urls')),
    path('kids/', include('kids.urls')),
]

kids/urls.py
from django.urls import path
from .views import (
    Kid_AllListView, kid_salon, kid_oyoc, kid_pw, kid_nb
)

app_name = 'veronahuang'
urlpatterns = [
    path('', Kid_AllListView.as_view(), name="base_kid"),
    path('home', Kid_AllListView.as_view(), name="home_kid"),
    path('salon', kid_salon.as_view(), name="salon_kid"),
    path('oyoc', kid_oyoc.as_view(), name="oyoc_kid"),
    path('pw', kid_pw.as_view(), name="pw_kid"),
    path('nb', kid_nb.as_view(), name="nb_kid"),
]

todo/urls.py
from django.urls import path
from . import views
from rest_framework import routers
from .views import (AtDetailView, AtListView, CastleView, CpListView,
                    FlightCreateView, FlightMyListView, LocationView,
                    PfListView, PnListView, Price001ListView, Price002ListView,
                    Price003ListView, Price004ListView, PtListView,
                    ServiceListView, SgListView, StudioListView,
                    Wedding01ListView, Wedding02ListView, Wedding03ListView,
                    Wedding04ListView, WeddingDeleteView,
                    WeddingDetailView, WeddingListView,
                    WeddingUpdateView, YoutubeListView, FamilyListView, DetailAPIview,
                    ListCreateAPIView, OverseaListView)

app_name = 'todo'
router = routers.DefaultRouter()
router.register('apiset', views.ApiForm001)

urlpatterns = [
    path('', WeddingListView.as_view(), name='list'),
    path('studio', StudioListView.as_view(), name='studio'),
    path('studio-yt', YoutubeListView.as_view(), name='yt'),
    path('service', ServiceListView.as_view(), name='service'),
    path('price001', Price001ListView.as_view(), name='price001'),
    path('price002', Price002ListView.as_view(), name='price002'),
    path('price003', Price003ListView.as_view(), name='price003'),
    path('price004', Price004ListView.as_view(), name='price004'),
    path('pn', PnListView.as_view(), name='pn'),
    path('sg', SgListView.as_view(), name='sg'),
    path('pf', PfListView.as_view(), name='pf'),
    path('cp', CpListView.as_view(), name='cp'),
    path('pt', PtListView.as_view(), name='pt'),
    path('at', AtListView.as_view(), name='at'),
    path('fam', FamilyListView.as_view(), name='fam'),
    path('detail/<int:pk>', AtDetailView.as_view(), name='detail'),
    path('wed-01', Wedding01ListView.as_view(), name='wed-01'),
    path('wed-02', Wedding02ListView.as_view(), name='wed-02'),
    path('wed-03', Wedding03ListView.as_view(), name='wed-03'),
    path('wed-04', Wedding04ListView.as_view(), name='wed-04'),
    path('location', LocationView.as_view(), name='loa'),
    path('castle', CastleView.as_view(), name='cas'),
    path('mylist', FlightMyListView.as_view(), name='mylist'),
    path('create', FlightCreateView.as_view(), name='create'),
    path('update/<int:pk>', WeddingUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', WeddingDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>', WeddingDetailView.as_view(), name='detail'),
    path('form', ListCreateAPIView.as_view(), name='list001'),
    path('form/<str:pk>', DetailAPIview.as_view(), name='del-api'),
    path('os', OverseaListView.as_view(), name='os'),
]

todo/forms.py
from django import forms
from .models import Customer, Flight, Index_001
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextFormField
from ckeditor.widgets import CKEditorWidget


class IndexModelForm(forms.ModelForm):
    class Meta:
        model = Index_001
        fields = ('mid_ph_010', 'mid_ph_011', 'mid_ph_012', 'mid_001', 'mid_txt_001', 'mid_ph_001', 'mid_002', 'mid_txt_002', 'mid_ph_002',
                  'mid_003', 'mid_txt_003', 'mid_ph_003', 'mid_004', 'mid_txt_004', 'mid_ph_004',
                  'mid_005', 'mid_txt_005', 'mid_ph_005', 'mid_006', 'mid_txt_006', 'mid_ph_006',

                  )
        widgets = {
            'mid_001': forms.TextInput(attrs={}),
            'mid_txt_001': forms.Textarea(attrs={'cols': 40, 'row': 10}),
            'mid_002': forms.TextInput(attrs={}),
            'mid_txt_002': forms.Textarea(attrs={'cols': 40, 'row': 10}),
            'mid_003': forms.TextInput(attrs={}),
            'mid_txt_003': forms.Textarea(attrs={'cols': 40, 'row': 10}),
            'mid_004': forms.TextInput(attrs={}),
            'mid_txt_004': forms.Textarea(attrs={'cols': 40, 'row': 10}),
            'mid_005': forms.TextInput(attrs={}),
            'mid_txt_005': forms.Textarea(attrs={'cols': 40, 'row': 10}),
            'mid_006': forms.TextInput(attrs={}),
            'mid_txt_006': forms.Textarea(attrs={'cols': 40, 'row': 10}),
        }


class FlightModelForm(forms.ModelForm):
    """docstring for FlightModelForm"""

    class Meta:
        model = Flight
        fields = ('items', 'fromname', 'arrivalname',
                  'description', 'pd_number', 'pd_content',)
        widgets = {
            'items': forms.Select(choices=(('', '請選擇'),) + Flight.items_choices, attrs={'class': 'form-control'}),
            'fromname': forms.TextInput(attrs={'class': 'form-control', 'rows': '4'}),
            'arrivalname': forms.TextInput(attrs={'class': 'form-control', 'rows': '4'}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'rows': '4'}),
            'pd_number': forms.TextInput(attrs={'class': 'form-control', 'rows': '4'}),
            'pub_date': forms.TextInput(attrs={'class': 'form-control', 'rows': '4'}),
        }


class RegisterForm(UserCreationForm):
    username = forms.CharField(
        label="帳號",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    email = forms.EmailField(
        label="電子郵件",
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )
    password1 = forms.CharField(
        label="密碼",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    password2 = forms.CharField(
        label="密碼確認",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginForm(forms.Form):
    username = forms.CharField(
        label="帳號",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        label="密碼",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )


class CustomerModelForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'style': 'width:50%;'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'style': 'width:50%;'}),
            'tel': forms.TextInput(attrs={'class': 'form-control', 'style': 'width:50%;'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'style': 'width:20%'})
        }
        labels = {
            'name': '姓名',
            'email': '電子郵件',
            'tel': '聯絡電話',
            'password': '密碼',
        }

todo/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm, LoginForm, CustomerModelForm
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import auth
from .models import Member, Flight, Index_001, Pn_001, Price_003, Price_004, Studio_001, Service_001, Price_001, Price_002, Price_003, Price_004, Pn_001, Sg_001, Pf_001, Cp_001, Pt_001, at_001, Wedding_01, Wedding_02, Wedding_03, Wedding_04, location_01, castle_01, youtube_studio, family_01, wedding_form_001, os_001
from .forms import FlightModelForm, IndexModelForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .serializers import wedding_serializer
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from rest_framework import generics
from .filters import FlightFilter
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView
)


class ListCreateAPIView(generics.ListCreateAPIView):
    queryset = wedding_form_001.objects.all()
    serializer_class = wedding_serializer


class DetailAPIview(generics.RetrieveUpdateDestroyAPIView):
    queryset = wedding_form_001.objects.all()
    serializer_class = wedding_serializer


class ApiForm001(ModelViewSet):
    queryset = wedding_form_001.objects.all()
    serializer_class = wedding_serializer


@api_view(['GET'])
def weddinglistapi(request):
    Apilists = wedding_form_001.objects.all()
    serializer = wedding_serializer(Apilists, many=True)
    return Response(serializer.data)


class FlightListView(ListView):
    model = Index_001
    queryset = Flight.objects.filter(finish=False)  # 指定查詢條件
    template_name = 'flight/flight_main.html'  # 樣板路徑

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(FlightListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = FlightFilter(
            self.request.GET, queryset=self.get_queryset())  # 資料模型表單
        return context


class FlightMyListView(LoginRequiredMixin, ListView):
    model = Index_001
    template_name = 'flight/flight_self.html'

    # 要傳遞的資料
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = IndexModelForm()  # 資料模型表單
        return context


class FlightCreateView(CreateView):
    model = Index_001
    form_class = IndexModelForm  # 使用的表單類別

    success_url = '/flight/mylist'  # 儲存成功後要導向的網址

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(FlightCreateView, self).form_valid(form)
# wedding


class WeddingListView(ListView):
    model = Index_001
    template_name = 'flight/wedding_main.html'  # 樣板路徑


class StudioListView(ListView):
    model = Studio_001
    template_name = 'flight/studio.html'  # 樣板路徑


class ServiceListView(ListView):
    model = Service_001
    template_name = 'flight/service.html'  # 樣板路徑


class Price001ListView(ListView):
    model = Price_001
    template_name = 'flight/price-001.html'  # 樣板路徑


class Price002ListView(ListView):
    model = Price_002
    template_name = 'flight/price-002.html'  # 樣板路徑


class Price003ListView(ListView):
    model = Price_003
    template_name = 'flight/price-003.html'  # 樣板路徑


class Price004ListView(ListView):
    model = Price_004
    template_name = 'flight/price-004.html'  # 樣板路徑


class PnListView(ListView):
    model = Pn_001
    template_name = 'flight/pn-001.html'  # 樣板路徑


class SgListView(ListView):
    model = Sg_001
    template_name = 'flight/sg-001.html'  # 樣板路徑


class PfListView(ListView):
    model = Pf_001
    template_name = 'flight/pf-001.html'  # 樣板路徑


class CpListView(ListView):
    model = Cp_001
    template_name = 'flight/cp-001.html'  # 樣板路徑


class PtListView(ListView):
    model = Pt_001
    template_name = 'flight/pt-001.html'  # 樣板路徑


class AtListView(ListView):
    model = at_001
    template_name = 'flight/at-001.html'


class AtDetailView(DetailView):
    model = at_001
    template_name = 'flight/at_detail.html'


class Wedding01ListView(ListView):
    model = Wedding_01
    template_name = 'flight/wedding.html'  # 樣板路徑


class Wedding02ListView(ListView):
    model = Wedding_02
    template_name = 'flight/wedding_02.html'  # 樣板路徑


class Wedding03ListView(ListView):
    model = Wedding_03
    template_name = 'flight/wedding_03.html'  # 樣板路徑


class Wedding04ListView(ListView):
    model = Wedding_04
    template_name = 'flight/wedding_04.html'  # 樣板路徑


class LocationView(ListView):
    model = location_01
    template_name = 'flight/location.html'


class CastleView(ListView):
    model = castle_01
    template_name = 'flight/castle.html'


class YoutubeListView(ListView):
    model = youtube_studio
    template_name = 'flight/studio-yt.html'  # 樣板路徑


class OverseaListView(ListView):
    model = os_001
    template_name = 'flight/os_001.html'  # 樣板路徑


class FamilyListView(ListView):
    model = family_01
    template_name = 'flight/fam.html'  # 樣板路徑


class WeddingCreateView(CreateView):
    model = Index_001
    form_class = IndexModelForm  # 使用的表單類別

    success_url = '/flight/mylist'  # 儲存成功後要導向的網址

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(WeddingCreateView, self).form_valid(form)


class WeddingUpdateView(UpdateView):
    model = Index_001
    form_class = IndexModelForm  # 使用的表單類別
    queryset = Index_001.objects.all()  # 這很重要
    template_name = 'flight/flight_update.html'  # 修改樣板
    success_url = '/flight/mylist'  # 儲存成功後要導向的網址

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)


class WeddingDeleteView(DeleteView):
    model = Index_001
    template_name = 'flight/flight_delete.html'  # 刪除樣板
    success_url = '/flight/mylist'  # 刪除成功後要導向的網址


class WeddingDetailView(DetailView):
    model = Index_001
    template_name = 'flight/flight_detail.html'

todo/templates/flight/cp-001.html
{% extends 'base.html' %} {% block content %} {% load static %}
<link rel="stylesheet" href="{% static 'assets/css/templatemo-style.css' %}">
<main id="main">

    <!-- ======= Blog Section ======= -->
    <section class="hero-section inner-page">
        <div class="wave">

            <svg width="1920px" height="265px" viewBox="0 0 1920 265" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
            <g id="Apple-TV" transform="translate(0.000000, -402.000000)" fill="#FFFFFF">
              <path d="M0,439.134243 C175.04074,464.89273 327.944386,477.771974 458.710937,477.771974 C654.860765,477.771974 870.645295,442.632362 1205.9828,410.192501 C1429.54114,388.565926 1667.54687,411.092417 1920,477.771974 L1920,667 L1017.15166,667 L0,667 L0,439.134243 Z" id="Path"></path>
            </g>
          </g>
        </svg>

        </div>

        <div class="container">
            <div class="row align-items-center">
                <div class="col-12">
                    <div class="row justify-content-center">
                        <div class="col-md-7 text-center hero-text">
                            <h1 data-aos="fade-up" data-aos-delay="">情侶寫真</h1>
                            <p class="mb-5" data-aos="fade-up" data-aos-delay="100" style="font-family: 'Poppins', sans-serif !important;">Couple</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>

    <!-- MAIN POSTS -->
    <section>
        <hr>
        <div class="site-section">
            <div class="container ">
                <div class="justify-content-center text-center mb-4">
                    <div class="">
                        <div class="blog-masonry masonry-true">

                            {% for todo in object_list %}
                            <div class="post-masonry col-md-4 col-sm-6">
                                <div class="post-thumb">
                                    <img src="{{ todo.cp_ph_001 }}">
                                </div>
                            </div>
                            <!-- /.post-masonry -->

                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        </div>



    </section>
    <!-- Modal ////-->
</main>
<!-- End #main -->
{% endblock %}

todo/templates/flight/flight_delete.html
{% extends 'base.html' %} {% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-6">
            <div class="card">
                <div class="card-body">
                    是否確定刪除{{ object.title }}?
                    <br />
                    <br />
                    <form action="" method="POST">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary" value="確定" />
                        <a href="{% url 'todo:list' %}" class="btn btn-warning">取消</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

todo/templates/flight/flight_detail.html
{% extends 'base.html' %} {% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-6">
            <div class="card">
                <div class="card-body">
                    <ul class="list-group list-group-flush" style="color:#000">
                        <li class="list-group-item">國家：{{ object.fromname }}</li>
                        <li class="list-group-item">種類：{{ object.items }}</li>
                        <li class="list-group-item">商品名稱：{{ object.arrivalname }}</li>
                        <li class="list-group-item">註明：{{ object.description }}</li>
                        <li class="list-group-item">商品內容：<br>{{ object.pd_content|safe }}</li>
                        <li class="list-group-item">日期：{{ object.pub_date }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>




{% endblock %}

todo/templates/flight/location.html
{% extends 'base.html' %} {% block content %} {% load static %}
<link rel="stylesheet" href="{% static 'assets/css/templatemo-style.css' %}">
<main id="main">

    <!-- ======= Blog Section ======= -->
    <section class="hero-section inner-page">
        <div class="wave">

            <svg width="1920px" height="265px" viewBox="0 0 1920 265" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
            <g id="Apple-TV" transform="translate(0.000000, -402.000000)" fill="#FFFFFF">
              <path d="M0,439.134243 C175.04074,464.89273 327.944386,477.771974 458.710937,477.771974 C654.860765,477.771974 870.645295,442.632362 1205.9828,410.192501 C1429.54114,388.565926 1667.54687,411.092417 1920,477.771974 L1920,667 L1017.15166,667 L0,667 L0,439.134243 Z" id="Path"></path>
            </g>
          </g>
        </svg>

        </div>

        <div class="container">
            <div class="row align-items-center">
                <div class="col-12">
                    <div class="row justify-content-center">
                        <div class="col-md-7 text-center hero-text">
                            <h1 data-aos="fade-up" data-aos-delay="">攝影地點</h1>
                            <p class="mb-5" data-aos="fade-up" data-aos-delay="100" style="font-family: 'Poppins', sans-serif !important;">Pre-wedding</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>

    <!-- MAIN POSTS -->
    <section>
        <hr>
        <div class="site-section">
            <div class="container ">
                <div class="justify-content-center text-center mb-4">
                    <div class="">
                        <div class="blog-masonry masonry-true">

                            {% for todo in object_list %}
                            <div class="post-masonry col-md-4 col-sm-6">
                                <div class="post-thumb">
                                    <img src="{{ todo.location_ph_001 }}">
                                </div>
                            </div>
                            <!-- /.post-masonry -->

                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        </div>



    </section>
    <!-- Modal ////-->
</main>
<!-- End #main -->
{% endblock %}

todo/templates/flight/pf-001.html
{% extends 'base.html' %} {% block content %} {% load static %}
<link rel="stylesheet" href="{% static 'assets/css/templatemo-style.css' %}">
<main id="main">

    <!-- ======= Blog Section ======= -->
    <section class="hero-section inner-page">
        <div class="wave">

            <svg width="1920px" height="265px" viewBox="0 0 1920 265" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
            <g id="Apple-TV" transform="translate(0.000000, -402.000000)" fill="#FFFFFF">
              <path d="M0,439.134243 C175.04074,464.89273 327.944386,477.771974 458.710937,477.771974 C654.860765,477.771974 870.645295,442.632362 1205.9828,410.192501 C1429.54114,388.565926 1667.54687,411.092417 1920,477.771974 L1920,667 L1017.15166,667 L0,667 L0,439.134243 Z" id="Path"></path>
            </g>
          </g>
        </svg>

        </div>

        <div class="container">
            <div class="row align-items-center">
                <div class="col-12">
                    <div class="row justify-content-center">
                        <div class="col-md-7 text-center hero-text">
                            <h1 data-aos="fade-up" data-aos-delay="">專業形象照</h1>
                            <p class="mb-5" data-aos="fade-up" data-aos-delay="100" style="font-family: 'Poppins', sans-serif !important;">Artistic</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>

    <!-- MAIN POSTS -->
    <section>
        <hr>
        <div class="site-section">
            <div class="container ">
                <div class="justify-content-center text-center mb-4">
                    <div class="">
                        <div class="blog-masonry masonry-true">

                            {% for todo in object_list %}
                            <div class="post-masonry col-md-4 col-sm-6">
                                <div class="post-thumb">
                                    <img src="{{ todo.pf_ph_001 }}">
                                </div>
                            </div>
                            <!-- /.post-masonry -->

                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        </div>



    </section>
    <!-- Modal ////-->
</main>
<!-- End #main -->
{% endblock %}

todo/templates/flight/price-001.html
{% extends 'base.html' %} {% block content %}

<main id="main">

    <!-- ======= Features Section ======= -->

    <section class="hero-section inner-page">
        <div class="wave">

            <svg width="1920px" height="265px" viewBox="0 0 1920 265" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
            <g id="Apple-TV" transform="translate(0.000000, -402.000000)" fill="#FFFFFF">
              <path d="M0,439.134243 C175.04074,464.89273 327.944386,477.771974 458.710937,477.771974 C654.860765,477.771974 870.645295,442.632362 1205.9828,410.192501 C1429.54114,388.565926 1667.54687,411.092417 1920,477.771974 L1920,667 L1017.15166,667 L0,667 L0,439.134243 Z" id="Path"></path>
            </g>
          </g>
        </svg>

        </div>

        <div class="container">
            <div class="row align-items-center">
                <div class="col-12">
                    <div class="row justify-content-center">
                        <div class="col-md-7 text-center hero-text">
                            <h1 data-aos="fade-up" data-aos-delay="">婚紗單拍</h1>
                            <p class="mb-5" data-aos="fade-up" data-aos-delay="100">Service</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>

    <section class="section pb-0">
        <div class="container">
            <div class="row align-items-center col-lg-12">

                <h2>婚紗單拍</h2><br>
                <hr>



                <div class="d-flex align-items-start">
                    <div class="nav flex-column nav-pills me-3 col-lg-2" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                        {% for todo in object_list %}
                        <button class="nav-link v-{{ todo.id }}" id="v-pills-home-tab v-{{ todo.id }}" data-bs-toggle="pill" data-bs-target="#v-pills{{ todo.id }}" type="button" role="tab" aria-controls="v-pills-home" aria-selected="true">{{ todo.price_btn_001 }}</button>                        {% endfor %}
                    </div>

                    <div class="tab-content col-lg-10" id="v-pills-tabContent">
                        {% for todo in object_list %}
                        <div class="tab-pane fade show active" id="v-pills{{ todo.id }}" role="tabpanel" aria-labelledby="v-pills-home-tab">
                            <div class="row ">
                                <p class="price-txt">
                                    {{ todo.price_txt_001|safe }}
                                </p>
                            </div>
                        </div>
                        {% endfor %}

                        <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
                            <div class="row ">
                                <p class="price-txt">

                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
<!-- End #main -->

{% endblock %}

todo/templates/flight/price-003.html
{% extends 'base.html' %} {% block content %}

<main id="main">

    <!-- ======= Features Section ======= -->

    <section class="hero-section inner-page">
        <div class="wave">

            <svg width="1920px" height="265px" viewBox="0 0 1920 265" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
            <g id="Apple-TV" transform="translate(0.000000, -402.000000)" fill="#FFFFFF">
              <path d="M0,439.134243 C175.04074,464.89273 327.944386,477.771974 458.710937,477.771974 C654.860765,477.771974 870.645295,442.632362 1205.9828,410.192501 C1429.54114,388.565926 1667.54687,411.092417 1920,477.771974 L1920,667 L1017.15166,667 L0,667 L0,439.134243 Z" id="Path"></path>
            </g>
          </g>
        </svg>

        </div>

        <div class="container">
            <div class="row align-items-center">
                <div class="col-12">
                    <div class="row justify-content-center">
                        <div class="col-md-7 text-center hero-text">
                            <h1 data-aos="fade-up" data-aos-delay="">同志寫真｜同性婚紗</h1>
                            <p class="mb-5" data-aos="fade-up" data-aos-delay="100">Service</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>

    <section class="section pb-0">
        <div class="container">
            <div class="row align-items-center col-lg-12">

                <h2>同志寫真｜同性婚紗</h2><br>
                <hr>



                <div class="d-flex align-items-start">
                    <div class="nav flex-column nav-pills me-3 col-lg-2" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                        {% for todo in object_list %}
                        <button class="nav-link v-{{ todo.id }}" id="v-pills-home-tab" data-bs-toggle="pill" data-bs-target="#v-pills{{ todo.id }}" type="button" role="tab" aria-controls="v-pills-home" aria-selected="true">{{ todo.price_btn_003 }}</button>                        {% endfor %}
                    </div>

                    <div class="tab-content col-lg-10" id="v-pills-tabContent">
                        {% for todo in object_list %}
                        <div class="tab-pane fade show active" id="v-pills{{ todo.id }}" role="tabpanel" aria-labelledby="v-pills-home-tab">
                            <div class="row ">
                                <p class="price-txt">
                                    {{ todo.price_txt_003|safe }}
                                </p>
                            </div>
                        </div>
                        {% endfor %}

                        <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
                            <div class="row ">
                                <p class="price-txt">

                                </p>
                            </div>

                        </div>

                    </div>
                </div>




            </div>
        </div>
    </section>



    <!-- ======= Testimonials Section ======= -->


</main>
<!-- End #main -->

{% endblock %}